//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class somaEntities : DbContext
    {
        public somaEntities()
            : base("name=somaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_PartType> M_PartType { get; set; }
        public virtual DbSet<M_User> M_User { get; set; }
        public virtual DbSet<T_Part> T_Part { get; set; }
        public virtual DbSet<M_Model> M_Model { get; set; }
        public virtual DbSet<M_ModelManufacturer> M_ModelManufacturer { get; set; }
        public virtual DbSet<M_ProductCategory> M_ProductCategory { get; set; }
        public virtual DbSet<M_SubType> M_SubType { get; set; }
    }
}
