//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PartSuppier
    {
        public int PartSuppierID { get; set; }
        public Nullable<int> PartID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string VendorPartNo { get; set; }
        public string VendorPartDescription { get; set; }
        public Nullable<decimal> Vendorprice { get; set; }
        public Nullable<decimal> Ourprice { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Note { get; set; }
        public bool Active { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual M_Vendor M_Vendor { get; set; }
        public virtual T_Part T_Part { get; set; }
    }
}
