//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Part
    {
        public int PartID { get; set; }
        public int SubTypeID { get; set; }
        public Nullable<int> ReplacementPartID { get; set; }
        public string PartNo { get; set; }
        public string PartDescription { get; set; }
        public string PartDetailDescription { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<int> Dim_L { get; set; }
        public Nullable<int> Dim_W { get; set; }
        public Nullable<int> Dim_H { get; set; }
        public Nullable<bool> Stockable { get; set; }
        public string OnlineMsg { get; set; }
        public string Note { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> Returnable { get; set; }
        public Nullable<bool> Publish { get; set; }
        public bool Active { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual T_Part T_Part1 { get; set; }
        public virtual T_Part T_Part2 { get; set; }
        public virtual M_SubType M_SubType { get; set; }
    }
}
