//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PartsCompatibility
    {
        public int PartLinkID { get; set; }
        public Nullable<int> PartID { get; set; }
        public int ProductCategoryID { get; set; }
        public string ProductCategoryDescription { get; set; }
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public int ModelID { get; set; }
        public string ModelNo { get; set; }
        public Nullable<int> ModelManufacturerId { get; set; }
        public bool Active { get; set; }
        public int CreatedBy { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
